import { Inter } from 'next/font/google'
import { Syne } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navtest'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })
const syne = Syne({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

     
     <body className={syne.className}>
        <Navbar font={syne.className} />
        {children}
      </body>
      <Footer font={syne.className} />
    </html>
  );
}
